---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  annotations:
    hypospray/testname: 05-node-selectors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: windows
      containers:
      - name: my-container
        image: nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
